Fix SetAttributes transforms failing on Mono.
Using Microsoft's Xml Document Transform library with a
xdt:Transform="SetAttributes" transform that updates attributes fails
when running on Mono with an Argument cannot be null exception.

Use custom build of the Microsoft.Web.XmlTransform assembly that
sets the prefix on XmlAttributes to an empty string instead of
null.

Microsoft.Web.XmlTransform.XmlNodeException: Argument cannot be null.
Parameter name: key ---> System.ArgumentNullException: Argument cannot be null.
Parameter name: key
  at System.Xml.NameTable.Add (System.String key) in
mcs/class/System.XML/System.Xml/NameTable.cs:92
  at System.Xml.XmlAttribute.set_Prefix (System.String value) in
mcs/class/System.XML/System.Xml/XmlAttribute.cs:197
  at
Microsoft.Web.XmlTransform.XmlElementContext.ScrubTransformAttributesAndNamespaces
(System.Xml.XmlNode node)
  at Microsoft.Web.XmlTransform.XmlElementContext.CreateCloneInTargetDocument
(System.Xml.XmlNode sourceNode)
  at Microsoft.Web.XmlTransform.XmlElementContext.get_TransformNode ()
  at Microsoft.Web.XmlTransform.Transform.get_TransformNode ()
  at Microsoft.Web.XmlTransform.Transform.ApplyOnAllTargetNodes ()
  at Microsoft.Web.XmlTransform.Transform.Execute
(Microsoft.Web.XmlTransform.XmlElementContext context, System.String
argumentString)
  --- End of inner exception stack trace ---
  at Microsoft.Web.XmlTransform.XmlTransformationLogger.LogErrorFromException
(System.Exception ex)
  at Microsoft.Web.XmlTransform.Transform.Execute
(Microsoft.Web.XmlTransform.XmlElementContext context, System.String
argumentString)
  at Microsoft.Web.XmlTransform.XmlTransformation.HandleElement
(Microsoft.Web.XmlTransform.XmlElementContext context)